-- stroyfoto — snapshot of database structure
-- Generated: 2026-05-02T14:55:33.481Z
-- PostgreSQL: PostgreSQL 17.9 (Ubuntu 17.9-201-yandex.59964.2288f7cd41) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0, 64-bit
-- Database: stroyfoto
-- This file is auto-generated by `npm run db:schema:pull`. Do not edit manually.
-- Source of truth for migrations: db/migrations/

-- ========================================================================
-- Schemas
-- ========================================================================


-- ========================================================================
-- Extensions
-- ========================================================================

CREATE EXTENSION IF NOT EXISTS "citext" WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA public;

-- ========================================================================
-- Enum types
-- ========================================================================

CREATE TYPE public.performer_kind AS ENUM ('contractor', 'own_forces');
CREATE TYPE public.user_role AS ENUM ('admin', 'user');

-- ========================================================================
-- Tables
-- ========================================================================

-- Table: public.app_users
CREATE TABLE public.app_users (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  email citext NOT NULL,
  password_hash text,
  password_must_reset boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  last_login_at timestamp with time zone,
  deleted_at timestamp with time zone
);

-- Table: public.performers
CREATE TABLE public.performers (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name citext NOT NULL,
  kind performer_kind NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public.plans
CREATE TABLE public.plans (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  project_id uuid NOT NULL,
  name text NOT NULL,
  object_key text NOT NULL,
  page_count integer,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  floor text,
  building text,
  section text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public.profiles
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text,
  role user_role DEFAULT 'user'::user_role NOT NULL,
  is_active boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public.project_memberships
CREATE TABLE public.project_memberships (
  project_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public.projects
CREATE TABLE public.projects (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  description text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public.refresh_tokens
CREATE TABLE public.refresh_tokens (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  token_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  last_used_at timestamp with time zone,
  revoked_at timestamp with time zone,
  replaced_by uuid,
  user_agent text,
  ip inet
);

-- Table: public.report_photos
CREATE TABLE public.report_photos (
  id uuid NOT NULL,
  report_id uuid NOT NULL,
  object_key text NOT NULL,
  thumb_object_key text,
  width integer,
  height integer,
  taken_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public.report_plan_marks
CREATE TABLE public.report_plan_marks (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  report_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  page integer NOT NULL,
  x_norm numeric(7,6) NOT NULL,
  y_norm numeric(7,6) NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public.reports
CREATE TABLE public.reports (
  id uuid NOT NULL,
  project_id uuid NOT NULL,
  work_type_id uuid NOT NULL,
  performer_id uuid NOT NULL,
  plan_id uuid,
  author_id uuid NOT NULL,
  description text,
  taken_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  work_assignment_id uuid
);

-- Table: public.work_assignments
CREATE TABLE public.work_assignments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name citext NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public.work_types
CREATE TABLE public.work_types (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name citext NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);


-- ========================================================================
-- Constraints
-- ========================================================================

ALTER TABLE public.app_users ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);
ALTER TABLE public.app_users ADD CONSTRAINT app_users_email_key UNIQUE (email);
ALTER TABLE public.performers ADD CONSTRAINT performers_pkey PRIMARY KEY (id);
ALTER TABLE public.performers ADD CONSTRAINT performers_kind_name_key UNIQUE (kind, name);
ALTER TABLE public.plans ADD CONSTRAINT plans_page_count_check CHECK (((page_count IS NULL) OR (page_count > 0)));
ALTER TABLE public.plans ADD CONSTRAINT plans_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.plans ADD CONSTRAINT plans_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.plans ADD CONSTRAINT plans_pkey PRIMARY KEY (id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.project_memberships ADD CONSTRAINT project_memberships_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.project_memberships ADD CONSTRAINT project_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.project_memberships ADD CONSTRAINT project_memberships_pkey PRIMARY KEY (project_id, user_id);
ALTER TABLE public.projects ADD CONSTRAINT projects_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.projects ADD CONSTRAINT projects_pkey PRIMARY KEY (id);
ALTER TABLE public.refresh_tokens ADD CONSTRAINT refresh_tokens_replaced_by_fkey FOREIGN KEY (replaced_by) REFERENCES refresh_tokens(id) ON DELETE SET NULL;
ALTER TABLE public.refresh_tokens ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE public.refresh_tokens ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);
ALTER TABLE public.refresh_tokens ADD CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash);
ALTER TABLE public.report_photos ADD CONSTRAINT report_photos_height_check CHECK (((height IS NULL) OR (height > 0)));
ALTER TABLE public.report_photos ADD CONSTRAINT report_photos_width_check CHECK (((width IS NULL) OR (width > 0)));
ALTER TABLE public.report_photos ADD CONSTRAINT report_photos_report_id_fkey FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE CASCADE;
ALTER TABLE public.report_photos ADD CONSTRAINT report_photos_pkey PRIMARY KEY (id);
ALTER TABLE public.report_plan_marks ADD CONSTRAINT report_plan_marks_page_check CHECK ((page > 0));
ALTER TABLE public.report_plan_marks ADD CONSTRAINT report_plan_marks_x_norm_check CHECK (((x_norm >= (0)::numeric) AND (x_norm <= (1)::numeric)));
ALTER TABLE public.report_plan_marks ADD CONSTRAINT report_plan_marks_y_norm_check CHECK (((y_norm >= (0)::numeric) AND (y_norm <= (1)::numeric)));
ALTER TABLE public.report_plan_marks ADD CONSTRAINT report_plan_marks_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE CASCADE;
ALTER TABLE public.report_plan_marks ADD CONSTRAINT report_plan_marks_report_id_fkey FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE CASCADE;
ALTER TABLE public.report_plan_marks ADD CONSTRAINT report_plan_marks_pkey PRIMARY KEY (id);
ALTER TABLE public.reports ADD CONSTRAINT reports_author_id_fkey FOREIGN KEY (author_id) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.reports ADD CONSTRAINT reports_performer_id_fkey FOREIGN KEY (performer_id) REFERENCES performers(id) ON DELETE RESTRICT;
ALTER TABLE public.reports ADD CONSTRAINT reports_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE SET NULL;
ALTER TABLE public.reports ADD CONSTRAINT reports_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE RESTRICT;
ALTER TABLE public.reports ADD CONSTRAINT reports_work_assignment_id_fkey FOREIGN KEY (work_assignment_id) REFERENCES work_assignments(id) ON DELETE SET NULL;
ALTER TABLE public.reports ADD CONSTRAINT reports_work_type_id_fkey FOREIGN KEY (work_type_id) REFERENCES work_types(id) ON DELETE RESTRICT;
ALTER TABLE public.reports ADD CONSTRAINT reports_pkey PRIMARY KEY (id);
ALTER TABLE public.work_assignments ADD CONSTRAINT work_assignments_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.work_assignments ADD CONSTRAINT work_assignments_pkey PRIMARY KEY (id);
ALTER TABLE public.work_assignments ADD CONSTRAINT work_assignments_name_key UNIQUE (name);
ALTER TABLE public.work_types ADD CONSTRAINT work_types_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.work_types ADD CONSTRAINT work_types_pkey PRIMARY KEY (id);
ALTER TABLE public.work_types ADD CONSTRAINT work_types_name_key UNIQUE (name);

-- ========================================================================
-- Indexes
-- ========================================================================

CREATE UNIQUE INDEX app_users_email_key ON public.app_users USING btree (email);
CREATE UNIQUE INDEX performers_kind_name_key ON public.performers USING btree (kind, name);
CREATE INDEX plans_project_idx ON public.plans USING btree (project_id);
CREATE INDEX profiles_role_idx ON public.profiles USING btree (role);
CREATE INDEX project_memberships_user_idx ON public.project_memberships USING btree (user_id);
CREATE UNIQUE INDEX projects_name_lower_uniq ON public.projects USING btree (lower(name));
CREATE INDEX refresh_tokens_active_idx ON public.refresh_tokens USING btree (user_id) WHERE (revoked_at IS NULL);
CREATE UNIQUE INDEX refresh_tokens_token_hash_key ON public.refresh_tokens USING btree (token_hash);
CREATE INDEX refresh_tokens_user_idx ON public.refresh_tokens USING btree (user_id);
CREATE INDEX report_photos_report_idx ON public.report_photos USING btree (report_id);
CREATE INDEX report_plan_marks_plan_idx ON public.report_plan_marks USING btree (plan_id);
CREATE UNIQUE INDEX report_plan_marks_report_uniq ON public.report_plan_marks USING btree (report_id);
CREATE INDEX reports_author_idx ON public.reports USING btree (author_id);
CREATE INDEX reports_project_created_idx ON public.reports USING btree (project_id, created_at DESC);
CREATE UNIQUE INDEX work_assignments_name_key ON public.work_assignments USING btree (name);
CREATE UNIQUE INDEX work_types_name_key ON public.work_types USING btree (name);

-- ========================================================================
-- Triggers
-- ========================================================================

CREATE TRIGGER set_app_users_updated_at BEFORE UPDATE ON public.app_users FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_plans_updated_at BEFORE UPDATE ON public.plans FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_projects_updated_at BEFORE UPDATE ON public.projects FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_reports_updated_at BEFORE UPDATE ON public.reports FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ========================================================================
-- Functions / Procedures
-- ========================================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'pg_catalog', 'pg_temp'
AS $function$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$function$
;

